log_level: DEBUG
words_address: localhost:8202
update_address: localhost:8101
token_ttl: 2m
search_concurrency: 1
search_rate: 1
rate_limiter: 100
concurrency_limiter: 10
http_server:
  address: localhost:28080
  timeout: 30s
