log_level: INFO
update_address: localhost:28082
words_address: localhost:28081
db_address: postgres://postgres:password@localhost:5432/postgres
index_ttl: 20s
xkcd:
  url: https://xkcd.com
  concurrency: 1000
  check_period: 1h
  timeout: 10s
